permalink: /:categories:month/:title
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
url: http://sozkoroglu.me
exclude:
        - Rakefile
        - Makefile
        - presentation.md
        - presentation.html
        - presentation.png
        - media

account: semihozkoroglu
archive: Son Girdiler
assets: /assets
author: Semih Özkoroğlu
disqus: 19notlar
email: sem@bil.omu.edu.tr
facebook: ~
feed: ~
flickr: ~
google: ~
googleanalyticsid: UA-23160847-1
googleplus: ~
gpg: ~
domain: sozkoroglu.me
logo: /assets/19/19-normal-128x128.png
organization: 19
picasa: ~
related: Diğer Girdiler
repository: semihozkoroglu.github.com
ribbon: GitHub'dayım
title: Semih Özköroğlu
twitter: ~

navigator:
        0: Teknik Olmayan Yazılar
        1: Teknik Yazılar

