author: Semih Özköroğlu - Blog
disqus: 19notlar
image: semih.jpg
markdown: redcarpet
paginate: 5
pygments: true
accounts:
- icon: icos-github
  url: https://github.com/semihozkoroglu
- icon: icos-google
  url: https://plus.google.com/105208314074645610795
- icon: icos-facebook
  url: https://www.facebook.com/semiiiih
- icon: icos-linkedin
  url: http://www.linkedin.com/profile/view?id=181945022
- icon: icos-twitter
  url: https://twitter.com/semihozkoroglu
- icon: icos-youtube
  url: http://www.youtube.com/channel/UCGMOH3R6gUxE9optqiSHUBw
next: Newer
previous: Older
tagline: Android Developer
home: Home
blog: Blog
latestpost: Posts
tag: Tags
copyright: Copyright © Sem 2013. All Rights Reserved.